name: Skypixel
version: '${project.version}'
main: com.koblizek.skypixel.Skypixel
api-version: 1.18
commands:
  test:
    usage: /test
  location:
    usage: /location <location>
  scoreboardreload:
    usage: /scoreboardreload
  setcoins:
    usage: /setcoins <type> <amount>
  transfercoins:
    usage: /transfercoins <from> <amount>